[package]
name = "sym-poly-multipoly"
version = "0.1.0"
edition = "2021"
description = "Multivariate polynomials with divided difference operators and key polynomials"

[dependencies]
combinatoric-core = { path = "../../combinatoric-core" }
sym-poly-core = { path = "../core" }
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
