[workspace]
members = [
    "polynomial-tools",
    "polynomial-tools/web",
    "polynomial-tools/mcp",
    "combinatoric-core",
    "combpoly",
    "kostka",
    "KTT-search",
    "experiments",
    "flagged-lorentzian",
    "polynomial-lab",
    "polynomial-lab/mcp",
    "sym-poly/core",
    "sym-poly/sym",
    "sym-poly/qsym",
    "sym-poly/multipoly",
]
resolver = "2"
