[package]
name = "combinatoric-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Shared library for combinatorics: partitions, compositions, symmetric functions"

[dependencies]
sym-poly-core = { path = "../sym-poly/core" }
sym-poly-sym = { path = "../sym-poly/sym" }
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
num-integer = "0.1"
