//! Finite lock polynomials from lock fillings.

use std::collections::BTreeMap;

use sym_poly_core::{Ring, Ssaf};

use crate::multipoly::MultiPoly;

/// Compute the finite lock polynomial indexed by a weak composition.
///
/// This is the weight enumerator of the lock fillings generated by
/// [`Ssaf::lock_fillings`].
pub fn lock_polynomial<C: Ring>(alpha: &[u32]) -> MultiPoly<C> {
    let num_vars = alpha.len();
    let mut terms: BTreeMap<Vec<u32>, C> = BTreeMap::new();

    for filling in Ssaf::lock_fillings(alpha) {
        let entry = terms.entry(filling.weight_vector()).or_insert_with(C::zero);
        *entry = entry.clone() + C::one();
    }

    MultiPoly::from_terms(num_vars, terms)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lock_polynomial_single_column_pair() {
        let lock: MultiPoly<i64> = lock_polynomial(&[1, 1]);
        assert_eq!(lock.terms().len(), 1);
        assert_eq!(lock.coefficient(&[1, 1]), 1);
    }

    #[test]
    fn test_lock_polynomial_single_row_length_two() {
        let lock: MultiPoly<i64> = lock_polynomial(&[2, 0]);
        assert_eq!(lock.terms().len(), 3);
        assert_eq!(lock.coefficient(&[2, 0]), 1);
        assert_eq!(lock.coefficient(&[1, 1]), 1);
        assert_eq!(lock.coefficient(&[0, 2]), 1);
    }

    #[test]
    fn test_lock_polynomial_counts_lock_fillings_by_weight() {
        let alpha = [2, 1, 1];
        let lock: MultiPoly<i64> = lock_polynomial(&alpha);
        let filling_count = Ssaf::lock_fillings(&alpha).len() as i64;
        let coefficient_sum: i64 = lock.terms().values().sum();

        assert_eq!(coefficient_sum, filling_count);
        assert!(lock
            .terms()
            .keys()
            .all(|weight| weight.iter().sum::<u32>() == alpha.iter().sum()));
    }
}
